=== LlamaGR1/hud-db/utils/hud-data.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "HUD Data",
  "description": "Data about a HUD",
  "type": "object",
  "required": ["name", "author", "repo", "hash", "resources"],
  "properties": {
    "name": {
      "title": "HUD Name",
      "description": "Display name of your HUD",
      "type": "string",
      "examples": ["My HUD"]
    },
    "author": {
      "description": "Display name of you, the active developer of the HUD (however, outdated HUD maintenance may not count as authoring in some cases)",
      "type": "string",
      "examples": ["Cool person"]
    },
    "contributors": {
      "description": "Display names of anyone you would like to credit for the creation/development of the HUD. Not to be used for general credits, but major and direct contributors",
      "type": "array",
      "items": {
        "type": "string"
      },
      "examples": ["Original creator, Previous maintainer"]
    },
    "releaseDate": {
      "description": "Initial release date of the HUD, YYYY-MM-DD",
      "type": "string",
      "format": "date",
      "examples": ["2009-12-31"]
    },
    "parent": {
      "description": "If this HUD is a slight edit of another, put its ID here. This will group the HUDs together.",
      "type": "string",
      "pattern": "^[\\w][\\w.-]*$",
      "examples": ["their-hud"]
    },
    "distinguishedFromParent": {
      "description": "If this HUD is a major update/edit to its parent, and thus should be listed separately from the parent HUD.",
      "type": "boolean"
    },
    "resources": {
      "description": "A list of image names/YouTube videos. Images are automatically converted to webp, do not use extensions for uploaded images. First resource is required, must be an image and is used as the display banner. Resources also support youtu.be links for video embeds.",
      "type": "array",
      "items": {
        "type": "string",
        "pattern": "^([\\w][\\w.-]*|https://youtu.be/[\\w-]+)$"
      },
      "minItems": 1,
      "maxItems": 15,
      "uniqueItems": true,
      "examples": ["myhud-banner, cool-image-1, https://youtu.be/21asadf"]
    },
    "social": {
      "title": "External Links",
      "description": "Links to your social media profiles and other pages",
      "type": "object",
      "properties": {
        "support": {
          "description": "A link people can use to support you financially",
          "type": "string",
          "format": "uri",
          "pattern": "^https://",
          "examples": ["https://ko-fi.com/super-duper-person"]
        },
        "issues": {
          "description": "An extra link where users can get help/report issues. If not present, will use GitHub Issues.",
          "format": "uri",
          "pattern": "^https://",
          "type": "string"
        },
        "steam_profile": {
          "description": "Your SteamID64",
          "type": "string",
          "pattern": "[^/][0-9]{8,}",
          "examples": ["76561191234567890"]
        },
        "steam_group": {
          "description": "Your Steam group vanity ID (used for custom URLs)",
          "type": "string",
          "pattern": "^([\\w-]){2,32}$",
          "examples": ["valve"]
        },
        "twitter": {
          "description": "Your Twitter handle",
          "type": "string",
          "pattern": "^(\\w){1,15}$",
          "examples": ["CoolPerson12812"]
        },
        "bsky": {
          "description": "Your BSky handle",
          "type": "string",
          "examples": ["coolerperson128123.bsky.social"]
        },
        "discord": {
          "description": "Your Discord server invite code, beginning with / (not the full URL), or your Discord in the format username#0",
          "type": "string",
          "pattern": "^((?=.{2,32}$)(?!(?:everyone|here)$)\\.?[a-z0-9_]+(?:\\.[a-z0-9_]+)*\\.?#0|/\\w+)$",
          "examples": ["vanity-or-invite"]
        },
        "youtube": {
          "description": "Your YouTube channel (either /channel/id URL, @username or channel name)",
          "type": "string",
          "pattern": "^(channel\\/UC[\\w-]{21}[AQgw]|(c\\/|user\\/)?[\\w@-]+)$",
          "examples": ["@TheCoolPerson"]
        },
        "twitch": {
          "description": "Your Twitch channel name",
          "type": "string",
          "pattern": "^[a-zA-Z0-9][\\w]{0,24}$",
          "examples": ["CoolPersonStreamer"]
        },
        "album": {
          "description": "Link to some Imgur album or other to provide more images",
          "type": "string",
          "format": "uri",
          "pattern": "^https://",
          "examples": ["https://imgur.com/a/fajsf"]
        }
      },
      "additionalProperties": false
    },
    "flags": {
      "title": "Features",
      "description": "A list of flags whose presence indicates the existence of a feature of some kind",
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "fonts",
          "menus",
          "scoreboards",
          "crosshairs",
          "minmode",
          "streamer-mode",
          "materials",
          "customization"
        ]
      },
      "uniqueItems": true
    },
    "traits": {
      "description": "Optional structured mapping of values",
      "type": "object",
      "properties": {
        "os": {
          "description": "What operating systems does the HUD support",
          "type": "array",
          "items": {
            "type": "string",
            "enum": ["windows", "mac", "linux"]
          },
          "uniqueItems": true
        },
        "gamemode": {
          "title": "Game Modes",
          "description": "What gamemodes does the HUD customize for",
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "tournament",
              "comp",
              "arena",
              "ad",
              "ctf",
              "cp",
              "halloween",
              "koth",
              "mannpower",
              "mvm",
              "pass",
              "pl",
              "plr",
              "pd",
              "rd",
              "sd",
              "tc"
            ]
          },
          "uniqueItems": true
        },
        "res": {
          "title": "Display Resolutions",
          "description": "What aspect ratios does the HUD support",
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "4/3",
              "16/9",
              "16/10",
              "21/9",
              "32/9",
              "17/9",
              "1/1",
              "5/4"
            ]
          },
          "uniqueItems": true
        },
        "position": {
          "description": "What position is the ammo/health in the HUD (multiple customization options can be available)",
          "type": "array",
          "items": {
            "type": "string",
            "enum": ["center", "corners", "default"]
          },
          "uniqueItems": true
        },
        "lang": {
          "title": "Languages",
          "description": "What languages does the HUD support (if it has custom language files)",
          "type": "array",
          "items": {
            "type": "string",
            "pattern": "^[a-z]{2}$"
          },
          "uniqueItems": true,
          "examples": ["en"]
        }
      },
      "additionalProperties": false
    },
    "tags": {
      "description": "A list of words associated with the HUD for discovery. Be general. First tag is considered primary and used as a category. There is no list of valid tags, but they are subject to review for usefulness/'spamminess'.",
      "type": "array",
      "items": {
        "type": "string",
        "pattern": "^[\\w-]+$"
      },
      "examples": ["minimal, monochrome"]
    },
    "repo": {
      "description": "GitHub repo web URL",
      "type": "string",
      "format": "uri",
      "pattern": "^https://",
      "examples": ["https://github.com/cool-person/myhud"]
    },
    "hash": {
      "description": "Git commit hash of your current version (PR an update to this each time your HUD updates, and we will approve it)",
      "type": "string",
      "examples": ["84c64d403a650b3ae4793c9d32e01b3383445740"]
    },
    "publishDate": {
      "description": "Date of publishing the current version (for non-GitHub HUD), YYYY-MM-DD",
      "type": "string",
      "format": "date"
    },
    "prerelease": {
      "description": "If this is a prerelease/WIP HUD",
      "type": "boolean"
    },
    "verified": {
      "description": "For internal use only to enable some functionality. Do not set this yourself.",
      "type": "boolean"
    },
    "usesReleases": {
      "description": "If the HUD uses GitHub releases for versioning and changelogs.",
      "type": "boolean"
    },
    "githubAuthor": {
      "description": "GitHub account used for profile information for the HUD.",
      "anyOf": [
        {
          "type": "string",
          "pattern": "^[a-zA-Z\\d](?:[a-zA-Z\\d]|-(?=[a-zA-Z\\d])){0,38}$"
        },
        { "type": "null" }
      ]
    }
  },
  "additionalProperties": false
}

=== LlamaGR1/hud-db/hud-data/ultrahud-tf2.json
{
  "name": "ULTRAHUD",
  "author": "Heaven Piercer",
  "contributors": [
    "raysfire",
    "Hypnotize",
    "Village Green Preserver",
    "Tomma",
    "techno"
  ],
  "parent": "rayshud",
  "distinguishedFromParent": true,
  "releaseDate": "2024-02-24",
  "resources": [
    "ultrareboot_banner"
  ],
  "flags": [
    "fonts",
    "menus",
    "crosshairs",
    "minmode",
    "customization",
    "streamer-mode",
    "materials"
  ],
  "repo": "https://github.com/heaven-piercer/ULTRAHUD-TF2",
  "hash": "fb977a2dbf66a38cd26e7c5b64f9b96e4937e26b",
  "prerelease": false,
  "social": {
    "discord": "/v8nmUKRX62",
    "album": "https://imgur.com/a/Y7q58Im"
  },
  "traits": {
    "os": [
      "windows"
    ],
    "gamemode": [
      "ad",
      "ctf",
      "cp",
      "koth",
      "mvm",
      "pl"
    ],
    "res": [
      "16/9"
    ],
    "position": [
      "center",
      "corners"
    ],
    "lang": [
      "en"
    ]
  }
}

=== LlamaGR1/hud-db/hud-data/bonerjamz-hud.json
{
  "name": "Bonerjamz HUD",
  "author": "polaco",
  "contributors": ["Hypnotize"],
  "social": {
    "album": "https://github.com/TF2HUDsArchive/Bonerjamz-Hud/blob/screenshots/showcase.md"
  },
  "repo": "https://github.com/TF2HUDsArchive/Bonerjamz-Hud",
  "githubAuthor": null,
  "hash": "314ac347613942bc25a35610768f6efccef9cc55",
  "resources": ["bonerjamz-hud-banner"]
}

=== LlamaGR1/hud-db/hud-data/producthud.json
{
  "name": "ProductHUD",
  "author": "Kruphixx",
  "contributors": [
    "omnibombulator",
    "Hypnotize",
    "Village Green Preserver",
    "quickkennedy",
    "techno"
  ],

  "releaseDate": "2024-05-08",
  "prerelease": false,

  "social": {
    "issues": "https://github.com/Kruphixx/producthud/issues",
    "steam_profile": "76561198138061435",
    "album": "https://github.com/Kruphixx/producthud/blob/screenshots/showcase.md"
  },

  "resources": [
    "product-banner-new",
    "product-menu-default",
    "product-menu-dark",
    "product-menu-green",
    "product-menu-purple",
    "product-loadout",
    "product-teamselect",
    "product-classselect",
    "product-health-default",
    "product-health-bottom",
    "product-uber",
    "product-payload",
    "product-mvm",
    "product-scoreboard"
  ],

  "flags": [
    "fonts",
    "menus",
    "scoreboards",
    "crosshairs",
    "minmode",
    "streamer-mode",
    "materials",
    "customization"
  ],

  "repo": "https://github.com/Kruphixx/producthud",
  "hash": "621289720ea4bc35c7b6d817decf7ea043bc3e2a",

  "traits": {
    "os": ["windows", "linux"],
    "gamemode": [
      "tournament",
      "comp",
      "arena",
      "ad",
      "ctf",
      "cp",
      "halloween",
      "koth",
      "mannpower",
      "mvm",
      "pass",
      "pl",
      "plr",
      "pd",
      "rd",
      "sd",
      "tc"
    ],
    "res": ["4/3", "16/9", "16/10", "21/9", "32/9", "17/9", "1/1", "5/4"],
    "position": ["center"]
  }
}

=== LlamaGR1/hud-db/hud-data/cb-hud.json
{
  "name": "CB HUD",
  "author": "ColdBalls",
  "contributors": ["Hypnotize"],
  "social": {
    "album": "https://github.com/TF2HUDsArchive/CB-Hud/blob/screenshots/showcase.md"
  },
  "repo": "https://github.com/TF2HUDsArchive/CB-Hud",
  "githubAuthor": null,
  "hash": "f9ca3c6ad87bb12ffa60bf42c9fa2094df22cb1e",
  "resources": ["cb-hud-banner"]
}

=== LlamaGR1/hud-db/hud-data/shlaner-hud.json
{
  "name": "Shlaner HUD",
  "author": "Shlaner",
  "contributors": ["Hypnotize"],
  "social": {
    "album": "https://github.com/TF2HUDsArchive/Shlaner-Hud/blob/screenshots/showcase.md"
  },
  "repo": "https://github.com/TF2HUDsArchive/Shlaner-Hud",
  "githubAuthor": null,
  "hash": "25a029bd82513c54d3d2bb742499487635877eb7",
  "resources": ["shlaner-hud-banner"]
}

=== LlamaGR1/hud-db/hud-data/m0rehud.json
{
  "name": "m0rehud",
  "author": "Hypnotize",
  "contributors": ["m0re"],
  "verified": true,
  "social": {
    "steam_profile": "76561198058754493",
    "album": "https://github.com/Hypnootize/m0rehud/blob/screenshots/showcase.md"
  },
  "flags": [
    "fonts",
    "menus",
    "scoreboards",
    "crosshairs",
    "minmode",
    "materials",
    "customization"
  ],
  "traits": {
    "os": ["windows", "linux"],
    "gamemode": [
      "tournament",
      "comp",
      "arena",
      "ad",
      "ctf",
      "cp",
      "halloween",
      "koth",
      "mannpower",
      "mvm",
      "pass",
      "pl",
      "plr",
      "pd",
      "rd",
      "sd",
      "tc"
    ],
    "res": ["4/3", "5/4", "16/9", "16/10"],
    "position": ["center"],
    "lang": ["en"]
  },
  "repo": "https://github.com/Hypnootize/m0rehud",
  "hash": "4f00092352c34d3317e195db5a5c414b0143a898",
  "resources": [
    "m0rehud-banner",
    "m0rehud-menu",
    "m0rehud-loadout",
    "m0rehud-customization",
    "m0rehud-buff",
    "m0rehud-low",
    "m0rehud-minmode",
    "m0rehud-medic",
    "m0rehud-scoreboard",
    "m0rehud-spectator"
  ]
}

=== LlamaGR1/hud-db/hud-data/middlemann.json
{
  "name": "Middle-Mann",
  "author": "Vexcenot",
  "social": {
    "support": "https://ko-fi.com/vexcenot",
    "steam_profile": "76561198170023074",
    "discord": "/9QzHkQx",
    "youtube": "@Vexcenot",
    "album": "https://imgur.com/a/B1572CO"
  },
  "flags": [
    "fonts",
    "menus",
    "scoreboards",
    "crosshairs",
    "materials",
    "customization"
  ],
  "traits": {
    "os": [
      "windows",
      "mac",
      "linux"
    ],
    "gamemode": [
      "tournament",
      "comp",
      "arena",
      "ad",
      "ctf",
      "cp",
      "halloween",
      "koth",
      "mannpower",
      "mvm",
      "pass",
      "pl",
      "plr",
      "pd",
      "rd",
      "sd",
      "tc"
    ],
    "res": [
      "1/1",
      "4/3",
      "5/4",
      "16/10",
      "16/9",
      "17/9",
      "21/9",
      "32/9"
    ],
    "position": [
      "center",
      "corners",
      "default"
    ],
    "lang": [
      "en"
    ]
  },
  "tags": [
    "minimal",
    "modern",
    "middle",
    "vanilla"
  ],
  "repo": "https://github.com/Vexcenot/-Middle-Mann",
  "hash": "96dbeffab2fd2674c26c2794f9350cf3e151dba0",
  "resources": [
    "middlemann-banner"
  ]
}

=== LlamaGR1/hud-db/hud-data/garm3n-7mf.json
{
  "name": "Garm3n 7MF",
  "author": "Garm3n",
  "contributors": ["Hypnotize"],
  "social": {
    "album": "https://github.com/TF2HUDsArchive/Garm3n-7MF/blob/screenshots/showcase.md"
  },
  "repo": "https://github.com/TF2HUDsArchive/Garm3n-7MF",
  "githubAuthor": null,
  "hash": "458657fe37357491731abc4f1f3fa8fe081c563f",
  "parent": "quakehud",
  "resources": ["garm3n-7mf-banner"]
}
